AppBundle\Entity\Decklist:
    type: entity
    table: decklist
    indexes:
        date_creation_index:
            columns: [ date_creation ]
        rotation_index:
            columns: [ rotation_id ]
        moderation_status_index:
            columns: [ moderation_status ]
    manyToOne:
        user:
            targetEntity: User
            nullable: false
            inversedBy: decklists
            joinColumn:
                name: user_id
                referencedColumnName: id
        identity:
            targetEntity: Card
            nullable: false
            inversedBy: decklists
            joinColumn:
                name: identity_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            nullable: false
            inversedBy: decklists
            joinColumn:
                name: faction_id
                referencedColumnName: id
        lastPack:
            targetEntity: Pack
            nullable: false
            inversedBy: decklists
            joinColumn:
                name: last_pack_id
                referencedColumnName: id
        parent:
            targetEntity: Deck
            nullable: true
            inversedBy: children
            joinColumn:
                name: parent_deck_id
                referencedColumnName: id
        precedent:
            targetEntity: Decklist
            nullable: true
            inversedBy: successors
            joinColumn:
                name: precedent_decklist_id
                referencedColumnName: id
        tournament:
            targetEntity: Tournament
            nullable: true
            inversedBy: decklists
            joinColumn:
                name: tournament_id
                referencedColumnName: id
        modflag:
            targetEntity: Modflag
            nullable: true
            inversedBy: decklists
            joinColumn:
                name: modflag_id
                referencedColumnName: id
        rotation:
            targetEntity: Rotation
            nullable: true
            inversedBy: decklists
            joinColumn:
                name: rotation_id
                referencedColumnName: id
        mwl:
            targetEntity: Mwl
            nullable: true
            joinColumn:
                name: mwl_id
                referencedColumnName: id
    oneToMany:
        slots:
            targetEntity: Decklistslot
            mappedBy: decklist
            cascade: ["persist","detach","remove"]
        comments:
            targetEntity: Comment
            mappedBy: decklist
            cascade: ["persist","detach","remove"]
        successors:
            targetEntity: Decklist
            mappedBy: precedent
        children:
            targetEntity: Deck
            mappedBy: parent
        legalities:
            targetEntity: Legality
            mappedBy: decklist
            cascade: ["remove"]
        claims:
            targetEntity: Claim
            mappedBy: decklist
            cascade: ["remove"]
    manyToMany:
        favorites:
            targetEntity: User
            inversedBy: favorites
            joinTable:
                name: favorite
                joinColumns:
                    decklist_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
            fetch: EXTRA_LAZY
            cascade: ["persist"]
        votes:
            targetEntity: User
            inversedBy: votes
            joinTable:
                name: vote
                joinColumns:
                    decklist_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
            fetch: EXTRA_LAZY
            cascade: ["persist"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            length: 36 
            nullable: true
            unique: true
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        name:
            type: string
            length: 60
        prettyname:
            type: string
            length: 60
        rawdescription:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        signature:
            type: string
            length: 32
        nbvotes:
            type: integer
        nbfavorites:
            type: integer
        nbcomments:
            type: integer
        dotw:
            type: integer
        moderationStatus:
            type: integer
            column: moderation_status
        isLegal:
            type: boolean
            column: is_legal
    lifecycleCallbacks: {  }
