AppBundle\Entity\Faction:
    type: entity
    table: faction
    repositoryClass: AppBundle\Repository\FactionRepository
    indexes:
        code_index:
            columns: [ code ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: faction
        decklists:
            targetEntity: Decklist
            mappedBy: faction
    manyToOne:
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
        name:
            type: string
            length: 255
        color:
            type: string
            length: 6
        isMini:
            type: boolean
            nullable: true
            column: is_mini
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
